site_name: "Alpha AI"
site_description: "Insights and articles on Artificial Intelligence"
site_author: "Harsh Malik"
site_url: "https://godhunter98.github.io/alpha_ai_blog/"

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.index

    
plugins:
  - blog
  - social
  - search

nav:
  - Home: index.md
  - Blog: 
      - Overview: blog/index.md
  - About: about.md

extra:
  #this is so that the made with mkdocs is not shown, but it's usage is not recommended
  generator: false

  #this is the footer and includes all our social media links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/godhunter98
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/harshshelby
    # - icon: fontawesome/brands/linkedin
      # link: https://www.linkedin.com/in/harshmalik98/
    - icon: fontawesome/brands/discord
      link: https://github.com/godhunter98